'use server';

import { generateObject } from 'ai';
import { z } from 'zod';
import { gemini } from '@/lib/ai';
import { createClient } from '@supabase/supabase-js';

// Schema for final verdict
const VerdictSchema = z.object({
  technicalScore: z.number().min(0).max(100).describe('Technical skills score from Round 2'),
  verdict: z.enum(['Strong Hire', 'Hire', 'Weak Hire', 'Reject']).describe('Final hiring decision'),
  summary: z.string().describe('2-sentence executive summary for the Hiring Manager'),
  technicalStrengths: z.array(z.string()).describe('Key technical strengths demonstrated'),
  technicalGaps: z.array(z.string()).describe('Areas of concern or knowledge gaps'),
  recommendation: z.string().describe('Specific recommendation for next steps'),
});

export type FinalVerdict = z.infer<typeof VerdictSchema>;

interface VerdictResult {
  success: boolean;
  verdict?: {
    score: number;
    verdict: string;
    summary: string;
  };
  fullVerdict?: FinalVerdict;
  error?: string;
}

export async function generateFinalVerdict(candidateId: string): Promise<VerdictResult> {
  try {
    // Initialize Supabase
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

    if (!supabaseUrl || !supabaseKey) {
      return { success: false, error: 'Supabase not configured' };
    }

    const supabase = createClient(supabaseUrl, supabaseKey);

    // Fetch candidate data including both rounds
    const { data: candidate, error: fetchError } = await supabase
      .from('candidates')
      .select('round_2_transcript, rating, job_description, job_id, full_name')
      .eq('id', candidateId)
      .single();

    if (fetchError || !candidate) {
      console.error('Failed to fetch candidate:', fetchError);
      return { success: false, error: 'Candidate not found' };
    }

    // Get job description and rubric from jobs table if not on candidate
    let jobDesc = candidate.job_description || '';
    let r2Rubric = '';
    if (candidate.job_id) {
      const { data: job } = await supabase
        .from('jobs')
        .select('description, title, r2_rubric')
        .eq('id', candidate.job_id)
        .single();

      if (job) {
        if (!jobDesc) jobDesc = `${job.title}: ${job.description || ''}`;
        r2Rubric = job.r2_rubric || '';
      }
    }

    const round2Transcript = candidate.round_2_transcript;
    const round1Score = candidate.rating || 0;

    if (!round2Transcript) {
      console.error('No Round 2 transcript found for candidate');
      return { success: false, error: 'No Round 2 transcript found' };
    }

    // Fetch configurable prompt from DB (fall back to hardcoded default)
    const FALLBACK_ROUND_2_PROMPT = `You are the Hiring Committee making a final decision on {candidate_name} after Round 2.

JOB: {job_description}

ROUND 1 SCORE (Personality/Drive): {round_1_score}/100

TECHNICAL ASSESSMENT RUBRIC:
{r2_rubric}

ROUND 2 TRANSCRIPT (Technical Interview):
{transcript}

STT NOTICE — SPEECH-TO-TEXT TRANSCRIPTION ERRORS:
This transcript was generated by an automated Speech-to-Text system. Phonetic errors are expected and are NOT the candidate's fault.
- Do NOT penalise mispronunciation of interviewer names or technical terms.
- Evaluate the candidate on their intent, substance, and ideas.

YOUR TASK:
Score the candidate on 5 weighted dimensions, then derive the overall technicalScore:

SCORING DIMENSIONS:
1. Technical Depth (30%) — Can they explain implementation details, not just high-level concepts? Do they understand how things actually work internally?
2. Problem Solving (25%) — Did they demonstrate structured thinking under pressure? Can they navigate ambiguous or novel problems?
3. Learning Velocity (20%) — When presented with unfamiliar concepts, how quickly did they reason about them? Could they derive tradeoffs without prior knowledge?
4. Execution Track Record (15%) — Do they have concrete evidence of shipping complex things? Real metrics, real failures, real lessons learned?
5. Communication of Complexity (10%) — Can they explain hard things simply and precisely? Do they avoid buzzwords and give specific examples?

MINIMUM GATE RULES:
- If Technical Depth sub-score < 65: cap technicalScore at 64 and set verdict to Weak Hire or Reject.
- If Problem Solving sub-score < 70: cap technicalScore at 64 and set verdict to Weak Hire or Reject.
- Both gates must be passed for a Hire or Strong Hire verdict.

SCORING GUIDE:
- 80–100: Passed both gates comfortably, strong across most dimensions.
- 70–79: Passed both gates, solid on most dimensions with minor gaps.
- 55–69: Mixed — passed some gates but has notable gaps in depth or problem solving.
- 0–54: Failed one or both gates, or pervasive surface-level answers.

VERDICT OPTIONS:
- "Strong Hire" — Both gates passed, avg ≥ 80, clear technical A-player
- "Hire" — Both gates passed, avg ≥ 70, solid candidate
- "Weak Hire" — Mixed signals, mentorship required, borderline gates
- "Reject" — Failed one or both gates, not a technical fit`;

    let promptTemplate = FALLBACK_ROUND_2_PROMPT;
    try {
      const { data: dbPrompt } = await supabase
        .from('prompts')
        .select('system_prompt')
        .eq('name', 'round_2_scoring')
        .single();
      if (dbPrompt?.system_prompt) {
        promptTemplate = dbPrompt.system_prompt;
      }
    } catch (e) {
      console.warn('[Final Verdict] Failed to fetch prompt from DB, using fallback:', e);
    }

    const prompt = promptTemplate
      .replace(/\{candidate_name\}/g, candidate.full_name || 'this candidate')
      .replace(/\{job_description\}/g, jobDesc.substring(0, 1500) || 'Software Engineering Role')
      .replace(/\{round_1_score\}/g, String(round1Score))
      .replace(/\{r2_rubric\}/g, r2Rubric || 'No specific rubric provided. Assess technical depth based on the job description.')
      .replace(/\{transcript\}/g, round2Transcript.substring(0, 6000));

    const { object: fullVerdict } = await generateObject({
      model: gemini,
      schema: VerdictSchema,
      prompt,
    });

    // Extract backward-compatible format
    const verdict = {
      score: fullVerdict.technicalScore,
      verdict: fullVerdict.verdict,
      summary: fullVerdict.summary,
    };

    // Update the candidate record
    const { error: updateError } = await supabase
      .from('candidates')
      .update({
        round_2_rating: verdict.score,
        final_verdict: verdict.verdict,
        full_verdict: fullVerdict,
        current_stage: 'completed',
        status: 'COMPLETED',
      })
      .eq('id', candidateId);

    if (updateError) {
      console.error('Failed to update candidate with verdict:', updateError);
      return { success: false, error: 'Failed to save verdict' };
    }

    console.log(`[Final Verdict] Candidate ${candidateId}: ${verdict.verdict} (Technical: ${verdict.score}/100)`);

    return { success: true, verdict, fullVerdict };

  } catch (error) {
    console.error('Generate final verdict error:', error);
    return { success: false, error: 'Failed to generate verdict' };
  }
}
